import user1 from "@/assets/images/users/user-1.jpg";
import user2 from "@/assets/images/users/user-2.jpg";
import user3 from "@/assets/images/users/user-3.jpg";
import user4 from "@/assets/images/users/user-4.jpg";
import user5 from "@/assets/images/users/user-5.jpg";
import user6 from "@/assets/images/users/user-6.jpg";


import customer1 from "@/assets/images/all-img/customer_1.png";
export const advancedTable = [
  {
    id: 1,
    order: 9,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "AC",
    date: "3/26/2022",
    quantity: 13,
    amount: "$1779.53",
    status: "Active",
    action: null,
  },
  {
    id: 2,
    order: 2,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "TV",
    date: "2/6/2022",
    quantity: 13,
    amount: "$2215.78",
    status: "Inactive",
    action: null,
  },
  {
    id: 3,
    order: 3,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "Fridge",
    date: "9/6/2021",
    quantity: 1,
    amount: "$3183.60",
    status: "Inactive",
    action: null,
  },
  {
    id: 4,
    order: 3,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "AC",
    date: "11/7/2021",
    quantity: 13,
    amount: "$2587.86",
    status: "Active",
    action: null,
  },
  {
    id: 5,
    order: 5,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "Washing Machine",
    date: "5/6/2022",
    quantity: 12,
    amount: "$3840.73",
    status: "Active",
    action: null,
  },
  {
    id: 6,
    order: 5,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "TV",
    date: "2/14/2022",
    quantity: 12,
    amount: "$4764.18",
    status: "Active",
    action: null,
  },
  {
    id: 7,
    order: 7,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "Washing Machine",
    date: "7/30/2022",
    quantity: 6,
    amount: "$2875.05",
    status: "Active",
    action: null,
  },
  {
    id: 8,
    order: 2,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "TV",
    date: "6/30/2022",
    quantity: 9,
    amount: "$2491.02",
    status: "Inactive",
    action: null,
  },
  {
    id: 9,
    order: 8,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "Washing Machine",
    date: "8/9/2022",
    quantity: 8,
    amount: "$3006.95",
    status: "Inactive",
    action: null,
  },
  {
    id: 10,
    order: 3,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "Washing Machine",
    date: "8/4/2022",
    quantity: 12,
    amount: "$2160.32",
    status: "Active",
    action: null,
  },
  {
    id: 11,
    order: 1,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "AC",
    date: "4/5/2022",
    quantity: 8,
    amount: "$1272.66",
    status: "Active",
    action: null,
  },
  {
    id: 12,
    order: 8,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "TV",
    date: "8/9/2022",
    quantity: 2,
    amount: "$4327.86",
    status: "Active",
    action: null,
  },
  {
    id: 13,
    order: 5,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "TV",
    date: "2/10/2022",
    quantity: 11,
    amount: "$3671.81",
    status: "Active",
    action: null,
  },
  {
    id: 14,
    order: 3,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "AC",
    date: "2/10/2022",
    quantity: 2,
    amount: "$3401.82",
    status: "Active",
    action: null,
  },
  {
    id: 15,
    order: 3,
    customer: {
      name: "Jenny Wilson",
      image: customer1,
    },
    product: "Fridge",
    date: "5/20/2022",
    quantity: 4,
    amount: "$2387.49",
    status: "Active",
    action: null,
  }
];

